title: SMS Guide
remote_theme: just-the-docs/just-the-docs@v0.4.0.rc3
color_scheme: dark
markdown: kramdown
kramdown:
  parse_block_html: true

collections:
  general:
    permalink: "/:collection/:path/"
    output: true
  game:
    permalink: "/:collection/:path/"
    output: true
  community:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    general:
      name: General
    game:
      name: Game
    community:
      name: Community
